version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pwd
            # Update the apt package index
            sudo apt-get update
            # Install AWS CLI
            sudo apt-get -y install awscli
            aws --version
            # Configure AWS CLI
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
            # Install Terraform CLI
            sudo apt-get install -y gnupg software-properties-common
            wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
            gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt update
            sudo apt-get -y install terraform
            terraform --version
      - setup_remote_docker
      - run:
          name: Deploy state architecture
          command: |
            pwd
            cd .state/terraform
            terraform init
            terraform apply --auto-approve
      - run:
          name: Deploy ECR if not exist and log into ECR
          command: |
            pwd
            cd .service/terraform
            terraform init
            terraform apply --target=module.ecr.aws_ecr_repository.ecr_repo --auto-approve
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_REPO_URL
      - run:
          name: Deploy cicd architecture
          command: |
            pwd
            cd .cicd/terraform
            terraform init -backend-config="bucket=$(cd .state/terraform && terraform output -raw cicd_terraform_state_bucket)" -backend-config="region=$AWS_REGION"
            terraform apply --auto-approve
      - run:
          name: Build, tag, and push Docker image to ECR
          command: |
            pwd
            docker build -t $IMAGE_NAME:$CIRCLE_SHA1 .
            docker tag $IMAGE_NAME:$CIRCLE_SHA1 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$CIRCLE_SHA1
            aws ecr describe-repositories --repository-names $AWS_ECR_REPO_NAME || $(cd .service/terraform && terraform init && terraform apply --target=module.ecr.aws_ecr_repository.ecr_repo --auto-approve)
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$CIRCLE_SHA1
      - run:
          name: Apply Terraform architecture changes
          command: |
            pwd
            cd .cicd/terraform
            terraform init 
            terraform apply -auto-approve
            cd ../../.service/terraform
            terraform init -backend-config="bucket=$(cd .state/terraform && terraform output -raw service_terraform_state_bucket)" -backend-config="region=$AWS_REGION"
            terraform apply -auto-approve
      - run: Force redeploy service
        command: |
            pwd
            aws ecs update-service --cluster $(cd .service/terraform && terraform output -raw ecs_cluster_name) --service $(cd .service/terraform && terraform output -raw ecs_service_name) --force-new-deployment

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master