version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout



workflows:
  version: 2
  build-and-push:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: master
