version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # Update the apt package index
            sudo apt-get update
            # Install AWS CLI
            sudo apt-get -y install awscli
            # Ensure AWS CLI is working
            aws --version
      - setup_remote_docker
      - run:
          name: Build and tag Docker image
          command: |
            docker build -t $IMAGE_NAME:$CIRCLE_SHA1 .
            docker tag $IMAGE_NAME:$CIRCLE_SHA1 $AWS_ECR_REPO/$IMAGE_NAME:$CIRCLE_SHA1
      - aws-ecr/build-and-push-image:
            account-url: AWS_ECR_REPO
            aws-access-key-id: AWS_ACCESS_KEY_ID
            aws-secret-access-key: AWS_SECRET_ACCESS_KEY
            region: AWS_REGION
            dockerfile: Dockerfile
            path: ./
            repo: quest-app
            tag: $CIRCLE_SHA1
  terraform-apply:
    docker:
      - image: hashicorp/terraform:1.0.9
    working_directory: ~/repo/terraform
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install terraform
            terraform --version
            echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $BASH_ENV
            echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Apply Terraform architecture changes
          command: |
            cd .service/terraform
            terraform init
            terraform validate
            terraform plan
            terraform apply -auto-approve

workflows:
  version: 2
  deploy:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: master
      - terraform-apply:
          requires: [build-and-push]
          filters:
            branches:
              only: master