version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # Update the apt package index
            sudo apt-get update
            # Install AWS CLI
            sudo apt-get -y install awscli
            # Ensure AWS CLI is working
            aws --version
      - setup_remote_docker
      - run:
          name: Build, tag, and push Docker image to ECR
          command: |
            docker build -t $SERVICE .
            docker tag $SERVICE:$CIRCLE_SHA1 $AWS_ECR_REPO:$CIRCLE_SHA1
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_REPO
            docker push $AWS_ECR_REPO/$IMAGE_NAME:$CIRCLE_SHA1
  terraform-apply:
    docker:
      - image: hashicorp/terraform:1.0.9
    working_directory: ~/repo/terraform
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install terraform
            terraform --version
            echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $BASH_ENV
            echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Apply Terraform architecture changes
          command: |
            terraform init
            terraform validate
            terraform plan
            terraform apply -auto-approve

workflows:
  version: 2
  deploy:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: master
      - terraform-apply:
          requires: [build-and-push]
          filters:
            branches:
              only: master